### GET cash cards
GET http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCIsImNhc2hjYXJkOndyaXRlIl19.ULCHspspPUfjhonTsO7YWk8UtKntU4jmU5OUvuak4cSOZCPj1FvVvzhZTFK3PY_yirRm8l6JJCl4jJp7IOomwMd6ClV10PrjNnVx8jtel6nzGuAmkT_ec5x6ye9ae1qsFkJKmki_dyO-AWpsG8eQhpRJhHn0XTN7Kbdud1CFvPOn0EaNIMUxYnZjTLukJC3mmWPj4wquuJ4GT574mVl4IVizICe9mUrGdBIB5Hl8TTtGbZIdXIjGqASe8gdNpvD5pl_qFXY3_vHyCnmTZy1yyTtLj4vFjSpGCYvDDMvOzVZ_Og0MS4OglOzbXXgKvJlgpZ_SeqamBAZ2RZ7KviLaqg

### GET cash cards (invalid token)
GET http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjE3MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMiwic2NwIjpbImNhc2hjYXJkOnJlYWQiLCJjYXNoY2FyZDp3cml0ZSJdfQ.nTqi8wxNt1FyDFmzl7CeolJ2aWhkxHY4cShGD8uWWp1etmqRZ4qZVCsoo2tHiPHMLY0ZvJKy7mNKRg5AWXAO2Ij1yqt6eO7x587IsFRH6Wy_5RqVO4BBszJUiEiWPVeD6LzBk7pOage2lA7e_UCT_Jf30l15NHvq3oj84N2Hm_9XwwUmfMU91WhVezPsvEZ32IkOxTht8N0cUCv4ENMLdOXpJovBNCcLd-ITgqs9R4zIN9t-YI3blYFJnWTgxMpfooNNryBn9M06BB40krvHioeS9KFKYMIuMpIN3-Ny4rRKFpYGgdetWxmo1bfTXBZ3vR-RPIJK_Sxs2MmzxeLTKg

### GET cash cards (get only token)
GET http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCJdfQ.mk9bWmQB7nr9ckcFUAEJ8pBsdAOLl18bqAQ75GnaUzh-NmSwcz_QsWbPsvhM-c5992_vwQoCjCM0qX-GK0OC29pjQGR28Pi6T5KE5KR8aw6vqiGvNfNS8HY9H9_JcFvbpa3_ntnK9yZ5NeUfcuyzjxjNb3kpQvJuaCem5DMzydnXuBlY9N7IhDP8bqgdimonzq69VbdMgATrRrz9Afjua-AAh98WkTSlmiMnGOJshtRqmjPMxIm6jTlyDzzJ0Xo8y7w1g76im7Zcy6myp8prWpriYZR1oyNzHTbqRTfIo2rfsJQBf-41ZTijjMODuu3N3j3KlHCI7Ji07NijYGlF0g

### POST cash cards (get only token)
POST http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCJdfQ.mk9bWmQB7nr9ckcFUAEJ8pBsdAOLl18bqAQ75GnaUzh-NmSwcz_QsWbPsvhM-c5992_vwQoCjCM0qX-GK0OC29pjQGR28Pi6T5KE5KR8aw6vqiGvNfNS8HY9H9_JcFvbpa3_ntnK9yZ5NeUfcuyzjxjNb3kpQvJuaCem5DMzydnXuBlY9N7IhDP8bqgdimonzq69VbdMgATrRrz9Afjua-AAh98WkTSlmiMnGOJshtRqmjPMxIm6jTlyDzzJ0Xo8y7w1g76im7Zcy6myp8prWpriYZR1oyNzHTbqRTfIo2rfsJQBf-41ZTijjMODuu3N3j3KlHCI7Ji07NijYGlF0g
Content-Type: application/json

{
"amount": 55.10
}

### POST cash cards
POST http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCIsImNhc2hjYXJkOndyaXRlIl19.ULCHspspPUfjhonTsO7YWk8UtKntU4jmU5OUvuak4cSOZCPj1FvVvzhZTFK3PY_yirRm8l6JJCl4jJp7IOomwMd6ClV10PrjNnVx8jtel6nzGuAmkT_ec5x6ye9ae1qsFkJKmki_dyO-AWpsG8eQhpRJhHn0XTN7Kbdud1CFvPOn0EaNIMUxYnZjTLukJC3mmWPj4wquuJ4GT574mVl4IVizICe9mUrGdBIB5Hl8TTtGbZIdXIjGqASe8gdNpvD5pl_qFXY3_vHyCnmTZy1yyTtLj4vFjSpGCYvDDMvOzVZ_Og0MS4OglOzbXXgKvJlgpZ_SeqamBAZ2RZ7KviLaqg
Content-Type: application/json

{
  "amount": 55.10
}

### GET cash by id (token sarah1)
GET http://localhost:8080/cashcards/99
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCIsImNhc2hjYXJkOndyaXRlIl19.ULCHspspPUfjhonTsO7YWk8UtKntU4jmU5OUvuak4cSOZCPj1FvVvzhZTFK3PY_yirRm8l6JJCl4jJp7IOomwMd6ClV10PrjNnVx8jtel6nzGuAmkT_ec5x6ye9ae1qsFkJKmki_dyO-AWpsG8eQhpRJhHn0XTN7Kbdud1CFvPOn0EaNIMUxYnZjTLukJC3mmWPj4wquuJ4GT574mVl4IVizICe9mUrGdBIB5Hl8TTtGbZIdXIjGqASe8gdNpvD5pl_qFXY3_vHyCnmTZy1yyTtLj4vFjSpGCYvDDMvOzVZ_Og0MS4OglOzbXXgKvJlgpZ_SeqamBAZ2RZ7KviLaqg

### GET cash by id (token esuez5) => access denied
GET http://localhost:8080/cashcards/99
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlc3VlejUiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCIsImNhc2hjYXJkOndyaXRlIl19.SCutQIGMV0116fxiHiCwHe-fC9ipBfAH0XbZ57S7ovb7JaT9nGrpwUPhER6Tni72tCKW57Du_Z3zXmfdMHjoj11DlD5qiR7o77WsnI8HQChNi44DSYjfeAbJXQaijM6N05Qn-NbqapDLGlmYolOciA8aF_ZlI2fHXaZcpQerLkHFi-bHMXMHwjqOf8fS90Xu-WqwzxAzszZ4LbST8mTfcP9PFON9-jWbBK7ib7wNbm2VS42GafcLoDC8reF-2iVy3fXFgJwLTRbCvWq2d1faVZW_mb-ojP_1pKeTxv3aJYoSimCk_n7xTb4K4so3pqjYQJmZTVZ-IeaYaHBA28sDUQ

### Request token
POST http://localhost:9000/oauth2/token
Authorization: Basic Y2FzaGNhcmQtY2xpZW50OnNlY3JldA== ### echo -n 'cashcard-client:secret' | base64
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=cashcard:read

### GET cash cards (OAuth2)
GET http://localhost:8080/cashcards
Authorization: Bearer eyJraWQiOiJhOEJVNk9uQW1kNkRNQnI4OXliZGJ2VGJOVHVjYmNlcEFNOWhsZzB0ekRJIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJjYXNoY2FyZC1jbGllbnQiLCJuYmYiOjE3MjcwNzU3NjQsInNjb3BlIjpbImNhc2hjYXJkOnJlYWQiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzI3MDc2MDY0LCJpYXQiOjE3MjcwNzU3NjR9.lL0DJve6N4D1Zvro_GWoZbeWks4YtcAlz6BeAVAzJNySLlDlYwcJdUjlAyrSJI6XlKOH9FGjt8y0DUOSsW46GRWOTBMZqcbu-QjMdc6TH76GXoY0E3ThImj7HUlUSm_tnstXzwpAa_2WPKNkuKePzpi8q5cRjCqfCMKLEOBpps2mW5n3RkUnI5j1h7BoaWVhAgqVm37JArAV1VRGHqhRoCOuhmBlU3Nj2BaupzoIZtPoTT_qtrdJTEWk2rbMh7zpcVGVuyEjAFLBbi59F54ZrRkhb-iBqeOvJ0uOhjEF3vVkxdaUUp7OIQ8MROYCQopY2min0kRjVJOUULpO9vDYxA
