### GET cash card
GET http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCIsImNhc2hjYXJkOndyaXRlIl19.ULCHspspPUfjhonTsO7YWk8UtKntU4jmU5OUvuak4cSOZCPj1FvVvzhZTFK3PY_yirRm8l6JJCl4jJp7IOomwMd6ClV10PrjNnVx8jtel6nzGuAmkT_ec5x6ye9ae1qsFkJKmki_dyO-AWpsG8eQhpRJhHn0XTN7Kbdud1CFvPOn0EaNIMUxYnZjTLukJC3mmWPj4wquuJ4GT574mVl4IVizICe9mUrGdBIB5Hl8TTtGbZIdXIjGqASe8gdNpvD5pl_qFXY3_vHyCnmTZy1yyTtLj4vFjSpGCYvDDMvOzVZ_Og0MS4OglOzbXXgKvJlgpZ_SeqamBAZ2RZ7KviLaqg
