### GET cash cards
GET http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjQ4ODA1MzAyNzUsImlhdCI6MTcyNjkzMDI3NSwic2NvcGUiOlsiY2FzaGNhcmQ6cmVhZCIsImNhc2hjYXJkOndyaXRlIl19.ULCHspspPUfjhonTsO7YWk8UtKntU4jmU5OUvuak4cSOZCPj1FvVvzhZTFK3PY_yirRm8l6JJCl4jJp7IOomwMd6ClV10PrjNnVx8jtel6nzGuAmkT_ec5x6ye9ae1qsFkJKmki_dyO-AWpsG8eQhpRJhHn0XTN7Kbdud1CFvPOn0EaNIMUxYnZjTLukJC3mmWPj4wquuJ4GT574mVl4IVizICe9mUrGdBIB5Hl8TTtGbZIdXIjGqASe8gdNpvD5pl_qFXY3_vHyCnmTZy1yyTtLj4vFjSpGCYvDDMvOzVZ_Og0MS4OglOzbXXgKvJlgpZ_SeqamBAZ2RZ7KviLaqg

### GET cash cards (invalid token)
GET http://localhost:8080/cashcards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjE3MTYyMzkwMjIsImlhdCI6MTUxNjIzOTAyMiwic2NwIjpbImNhc2hjYXJkOnJlYWQiLCJjYXNoY2FyZDp3cml0ZSJdfQ.nTqi8wxNt1FyDFmzl7CeolJ2aWhkxHY4cShGD8uWWp1etmqRZ4qZVCsoo2tHiPHMLY0ZvJKy7mNKRg5AWXAO2Ij1yqt6eO7x587IsFRH6Wy_5RqVO4BBszJUiEiWPVeD6LzBk7pOage2lA7e_UCT_Jf30l15NHvq3oj84N2Hm_9XwwUmfMU91WhVezPsvEZ32IkOxTht8N0cUCv4ENMLdOXpJovBNCcLd-ITgqs9R4zIN9t-YI3blYFJnWTgxMpfooNNryBn9M06BB40krvHioeS9KFKYMIuMpIN3-Ny4rRKFpYGgdetWxmo1bfTXBZ3vR-RPIJK_Sxs2MmzxeLTKg
